// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// ErrorSender is an autogenerated mock type for the ErrorSender type
type ErrorSender struct {
	mock.Mock
}

// AbortWithStatusJSON provides a mock function with given fields: ctx, err
func (_m *ErrorSender) AbortWithStatusJSON(ctx *gin.Context, err error) {
	_m.Called(ctx, err)
}

// JSON provides a mock function with given fields: ctx, err
func (_m *ErrorSender) JSON(ctx *gin.Context, err error) {
	_m.Called(ctx, err)
}

// JSONWithStatus provides a mock function with given fields: ctx, err, status
func (_m *ErrorSender) JSONWithStatus(ctx *gin.Context, err error, status int) {
	_m.Called(ctx, err, status)
}

type mockConstructorTestingTNewErrorSender interface {
	mock.TestingT
	Cleanup(func())
}

// NewErrorSender creates a new instance of ErrorSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewErrorSender(t mockConstructorTestingTNewErrorSender) *ErrorSender {
	mock := &ErrorSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
