// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RTwYrbMBD9FTMt9OLGzi6FRbctlO3eFlroIeSgOBNbiy2pM+OUJfjfy8h2kiYp9NKT",
	"jfTmvTdvRgeoQheDRy8M5gBcNdjZ9PuFKJD+RAoRSRymY5yP5S0iGGAh52sYcuiQ2dZ48y5aaW5esFjp",
	"E/EuUGcFDDgv93eQz1jnBWskBYvrkMV28Q/81gp+1KtTzcw/5ED4s3eEWzCrs/qjcD41dLI/mV0fycLm",
	"FStR/SdCFCW+SuXvvV9YmIHX9BoGVj05efumUxiJP1t21WM/ppemozUbPT2124hEGJTB+V1IJpy0evMU",
	"su/YxdYKZo8vz5DDHold8GBguSgXpbYVInobHRi4XywXyymBJF/UU8vFwdsOBz2rUfSzRa7IRRnJnlA4",
	"s9kMz345aTJpMKvdHn2mxZCUyGrF83as+YptG34EardJlWyHgsRgVpcCL0gc/AdOVJmEbIOjGmqpU0ia",
	"Ww5Jy8AkeQpfqMd82vBbg1ormGPwPEZ/V5b6qYIX9KllG2PrqtRA8cpq63DG5wS7VPiecAcG3hWnt1VM",
	"D6s4rtBwvQBDfhnqGfjT/3AzvvF/sZKQ2ZxP2laxtQ7q6JJhPZxvcRri2f6u1hoxI+3nCffUTtvLpija",
	"UNm2CSzmoXwoCxtdsV/CsB5+BwAA///bW8F1pQQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
