// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"time"
)

// Error defines model for Error.
type Error struct {
	Error     string    `json:"error"`
	Id        string    `json:"id"`
	Message   string    `json:"message"`
	Path      string    `json:"path"`
	Status    int32     `json:"status"`
	Timestamp time.Time `json:"timestamp"`
}

// GetUsersResponse defines model for GetUsersResponse.
type GetUsersResponse struct {
	Id   string `json:"id"`
	Name string `json:"name"`
}

// Greeting defines model for Greeting.
type Greeting struct {
	Message string `json:"message"`
}
