// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RUwYrbMBD9FTEt9OLGzi6FRbctlOzeFlroIeSg2BNbiy2po3HKEvzvZWQ7SZMUetmT",
	"xWjmvTfzRj5A6bvgHTqOoA8QywY7k47fiDzJIZAPSGwxhXEO81tA0BCZrKthyMBWN8MdxmhqvHkXDDc3",
	"LyIb7hPfzlNnGDRYx/d3kM251jHWSJLMtsPIpgt/5VeG8bNcnWpm/CEDwl+9JaxAr0X4OciRPZuaPfUw",
	"Kd4cEf32FUsWEStCZEG/mti/B3ChY068hpeJYNmT5bfv4tAI/NVEWz724wiTc1Kzleip54Y5wCAI1u18",
	"EmG5lZuVVz+wC61hVI8vz5DBHila70DDclEsCmnLB3QmWNBwv1gultMEEn1eTy3nB2c6HCRWI8unwliS",
	"DTyCrZCjMmpOV78tN4obVLXdo1NSDImJjFQ8V2PNE7at/+mprZ6Mq1qkRE6mQ0aKoNeXPC9I0btPMSEq",
	"9mqLIymKwVZSkn0ZJEoNE/PJA6Yes+kR3PJrI8kxeBdHB+6KQj6ld4wudW5CaG2Z+shfo8g6nOFZxi4V",
	"fiTcgYYP+en55dPby4+bNFzvwZBdzvYs+ct7qBl/A/8jJWWqeT5padnUYtRRZYTNcL7MycSzNV5vZMQR",
	"aT873FM7LXHUed760rSNj6wfiociN8Hm+yUMm+FPAAAA//+waKCsyAQAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
