// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RTzYrbMBB+FTEt9OLGzi6FRbctlOzeFlroIeSg2BNbiy2po3HKEvzuZWQ7SZMUetmT",
	"jTTz/cw3OkDpu+AdOo6gDxDLBjuTfr8ReZKfQD4gscV0jPMxvwUEDZHJuhqGDDqM0dR48y4Ybm5eRDbc",
	"J+Cdp84waLCO7+8gm2utY6yRpJhth5FNF/6qrwzjZ7k69cz4QwaEv3pLWIFen/UfibPJ0En+JHZzBPPb",
	"VyxZ+FeEyAJ8NZV/e7+QMBdew8swsOzJ8tt3SWEE/mqiLR/7cXopHenZyunJbsMcYBAE63Y+ibDcys3K",
	"qx/YhdYwqseXZ8hgjxStd6BhuSgWhdjyAZ0JFjTcL5aL5TSBRJ/Xk+X84EyHg5zVyPKpMJZkA49gK+So",
	"jJrL1W/LjeIGVW336JQ0Q2IiIx3P1djzhG3rf3pqqyfjqhYpkZPpkJEi6PUlzwtS9O5TTIiKvdriSIoV",
	"iH3QY3wZJEoNE/MpA6Yes2nRb+W1keIYvItjAndFIZ/SO0aXnJsQWlsmH/lrFFmHMzzL2KXGj4Q70PAh",
	"Pz2xfHpf+XGThus9GLLL2Z4Vf3kPNeNT/x8pqVLN80lLy6aWoI4qI2yG82VOIZ6t8XojI45I+znhntpp",
	"iaPO89aXpm18ZP1QPBS5CTbfL2HYDH8CAAD//4SBSgesBAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
